export const URL = {
  HOME_URL: "/",
  LOGIN_URL: "/auth/login",
  SIGNUP_URL: "/auth/signup",
  OAUTH_CALLBACK_URL: "/auth/callback",
  DASHBOARD_URL: "/dashboard",
  DASHBOARD_CONVERSATIONS_URL: "/dashboard/conversations",
  DASHBOARD_CONVERSATION_DETAILS_URL: "/dashboard/conversations/:id",
  AGENTS_URL: "/agents",
  AGENTS_RECONCILIATION_URL: "/agents/reconciliation",
  AGENTS_SUPPORT_URL: "/agents/support",
  AGENTS_FRAUD_URL: "/agents/fraud",
  AGENTS_RISK_URL: "/agents/risk",
  AGENTS_RELAY_URL: "/agents/relay",
  AGENTS_INSIGHTS_URL: "/agents/insights",
  AGENTS_FLOW_URL: "/agents/flow",
  AGENTS_FLOW_CONVERSATION_DETAILS_URL: "/agents/flow/conversations/:id",
  USERS_URL: "/users",
  STAFF_URL: "/staff",
  PRICING_URL: "/pricing",
  SETTINGS_URL: "/settings",
  ACCESS_CONTROL_FLOWS: "/auth/access-control-flows",
} as const;
