export const USER_TYPE = {
  SYS_ADMIN: "SYSTEM_ADMIN",
  DISTRIBUTION_MANAGER: "DISTRIBUTION_MANAGER",
  AGENT: "AGENT",
  USER: "USER",
  STAFF: "STAFF",
  MERCHANT: "MERCHANT",
  BUSINESS_AGGREGATOR: "BUSINESS_AGGREGATOR",
  INDIVIDUAL: "INDIVIDUAL",
  BUSINESS: "BUSINESS",
  AGENCY: "AGENCY",
  USER_STAFF: "USER_STAFF",
} as const;

export default USER_TYPE;
