export const USER_STATUS = {
  INVITED: "INVITED",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  REJECTED: "REJECTED",
  PENDING_APPROVAL: "PENDING_APPROVAL",
};

export default USER_STATUS;
